#include <algorithm>
#include <array>
#include <atomic>
#include <climits>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <stdexcept>
#include <string>
#include <unordered_set>
#include <vector>
#include <omp.h>
using namespace std;
namespace {
constexpr int L8=8388608, L9=67108864, R8=16777217;
constexpr int S9_MAX=115267902;
constexpr int MAX_R2=9474912, MAX_R4=76583776;
constexpr uint64_t S9_FNV=0x5005dc89644a7b80ULL;
constexpr uint64_t FNV_OFFSET=1469598103934665603ULL, FNV_PRIME=1099511628211ULL;
vector<int> uniq(vector<int> v){sort(v.begin(),v.end());v.erase(unique(v.begin(),v.end()),v.end());return v;}
vector<int> raw(const vector<int>&s,int R){vector<int>o;o.reserve(3*(s.size()+1));for(int k=0;k<3;k++)o.push_back(k*R);for(int x:s)for(int k=0;k<3;k++)o.push_back(x+k*R);return uniq(move(o));}
vector<int> tr(const vector<int>&v,int L){vector<int>o;o.reserve(v.size());for(int x:v)o.push_back(x+L);return o;}
vector<int> build_s8(){vector<int>H={0,1,2,16,17,18,21,22,23,26,27,28};vector<int>sc={64,256,2048,8192,32768};vector<int>Rs={61,303,1597,8195};vector<int>s;for(int x:H)s.push_back(64+x);s=uniq(move(s));for(int i=0;i<4;i++)s=tr(raw(s,Rs[i]),sc[i+1]);s=tr(raw(s,93476),262144);s=tr(raw(s,230164),1048576);s=tr(raw(s,2097164),L8);return s;}
vector<int> build_s9(){return tr(raw(build_s8(),R8),L9);}
int v2(int x){if(x<=0)throw invalid_argument("v2");return __builtin_ctz((unsigned)x);}
uint64_t fnv(const vector<int>&v){uint64_t h=FNV_OFFSET;for(int x:v){string t=to_string(x)+",";for(unsigned char b:t){h^=b;h*=FNV_PRIME;}}return h;}
vector<int> read_list(const string&p){FILE*f=fopen(p.c_str(),"r");if(!f)throw runtime_error("cannot open "+p);vector<int>v;int x;while(fscanf(f,"%d",&x)==1)v.push_back(x);fclose(f);return v;}
void write_list(const string&p,const vector<int>&v){FILE*f=fopen(p.c_str(),"w");if(!f)throw runtime_error("cannot write "+p);for(int x:v)fprintf(f,"%d\n",x);fclose(f);}
bool bit(const vector<uint64_t>&a,long long i){return i>=0&&(uint64_t)(i>>6)<a.size()&&((a[i>>6]>>(i&63))&1ULL);}
void save_bits(const string&p,long long low,const vector<uint64_t>&v){FILE*f=fopen(p.c_str(),"wb");if(!f)throw runtime_error("cannot write bits");uint64_t n=v.size();fwrite(&low,8,1,f);fwrite(&n,8,1,f);fwrite(v.data(),8,n,f);fclose(f);}
pair<long long,vector<uint64_t>> load_bits(const string&p){FILE*f=fopen(p.c_str(),"rb");if(!f)throw runtime_error("cannot open bits");long long low;uint64_t n;fread(&low,8,1,f);fread(&n,8,1,f);vector<uint64_t>v(n);fread(v.data(),8,n,f);fclose(f);return {low,move(v)};}
static inline void or_shift_right(const vector<uint64_t>&src,uint64_t shift,vector<uint64_t>&out){uint64_t sw=shift>>6;int sb=shift&63;if(sw>=src.size())return;size_t count=src.size()-sw;if(!sb){for(size_t w=0;w<count;w++)out[w]|=src[w+sw];}else{for(size_t w=0;w<count;w++){uint64_t q=src[w+sw]>>sb;if(w+sw+1<src.size())q|=src[w+sw+1]<<(64-sb);out[w]|=q;}}}
struct BaseData{vector<int>s8,A,g9,s9;};
BaseData data(){BaseData d;d.s8=build_s8();d.A={0};d.A.insert(d.A.end(),d.s8.begin(),d.s8.end());d.g9=raw(d.s8,R8);d.s9=tr(d.g9,L9);if(d.s9.size()!=88572||d.s9.front()!=L9||d.s9.back()!=S9_MAX||fnv(d.s9)!=S9_FNV)throw runtime_error("S9 mismatch");return d;}
struct Stats{vector<int>cnt,mn,mx;};
Stats base_stats(const vector<int>&A){int M=A.back();Stats s; s.cnt.assign(M+1,0);s.mn.assign(M+1,INT_MAX);s.mx.assign(M+1,INT_MIN);for(int i=0;i<(int)A.size();i++)for(int j=i+1;j<(int)A.size();j++){int d=A[j]-A[i];s.cnt[d]++;s.mn[d]=min(s.mn[d],A[i]);s.mx[d]=max(s.mx[d],A[i]);}return s;}
void mode_completions(const string&out){auto d=data();vector<int>B={0};B.insert(B.end(),d.s9.begin(),d.s9.end());int M=B.back();vector<unsigned char>present((size_t)M+1);for(int x:B)present[x]=1;long long low=-M,high=2LL*M,span=high-low+1;vector<uint64_t>bits((span+63)/64);double t=omp_get_wtime();
#pragma omp parallel for schedule(dynamic,8)
for(int i=0;i<(int)B.size();i++){int x=B[i];for(int j=i+1;j<(int)B.size();j++){int y=B[j];long long left=2LL*x-y,right=2LL*y-x;if(left>=0&&present[left]){long long k=right-low;__atomic_fetch_or(&bits[k>>6],1ULL<<(k&63),__ATOMIC_RELAXED);}if(right<=M&&present[right]){long long k=left-low;__atomic_fetch_or(&bits[k>>6],1ULL<<(k&63),__ATOMIC_RELAXED);}}}
long long count=0,minz=LLONG_MAX,maxz=LLONG_MIN;for(size_t w=0;w<bits.size();w++){uint64_t q=bits[w];count+=__builtin_popcountll(q);if(q){minz=min(minz,low+(long long)w*64+__builtin_ctzll(q));maxz=max(maxz,low+(long long)w*64+63-__builtin_clzll(q));}}if(count!=13923661||minz!=50331647||maxz!=134478523)throw runtime_error("completion geometry mismatch");save_bits(out,low,bits);cout<<"completion_count="<<count<<" range="<<minz<<","<<maxz<<" time="<<omp_get_wtime()-t<<"\n";}
void mode_correlate(const string&in,int start,int end,const string&out){auto [low,all]=load_bits(in);auto d=data();vector<int>B={0};B.insert(B.end(),d.s9.begin(),d.s9.end());end=min(end,(int)B.size());const int M=134478523;size_t words=((uint64_t)M+64)/64;vector<uint64_t>C(words),Cr(words);for(size_t w=0;w<all.size();w++){uint64_t q=all[w];while(q){int zbit=__builtin_ctzll(q);long long z=low+(long long)w*64+zbit;if(z>=0&&z<=M){C[z>>6]|=1ULL<<(z&63);int r=M-(int)z;Cr[r>>6]|=1ULL<<(r&63);}q&=q-1;}}int nth=omp_get_max_threads();vector<vector<uint64_t>>local(nth,vector<uint64_t>(words));
#pragma omp parallel
{int tid=omp_get_thread_num();auto&o=local[tid];
#pragma omp for schedule(dynamic,1)
for(int i=start;i<end;i++){int b=B[i];or_shift_right(C,b,o);or_shift_right(Cr,M-b,o);}}
vector<uint64_t>D(words);for(auto&o:local)for(size_t w=0;w<words;w++)D[w]|=o[w];save_bits(out,0,D);long long c=0;for(auto q:D)c+=__builtin_popcountll(q);cout<<"correlation_range="<<start<<","<<end<<" support="<<c<<"\n";}
void mode_reduce(const string&out,int argc,char**argv,int first){vector<uint64_t>D;for(int i=first;i<argc;i++){auto [low,x]=load_bits(argv[i]);if(low!=0)throw runtime_error("chunk low mismatch");if(D.empty())D.assign(x.size(),0);if(D.size()!=x.size())throw runtime_error("chunk size mismatch");for(size_t j=0;j<D.size();j++)D[j]|=x[j];}long long c=0;for(auto q:D)c+=__builtin_popcountll(q);if(c!=71129286)throw runtime_error("combined support mismatch");save_bits(out,0,D);cout<<"combined_difference_support="<<c<<"\n";}
vector<unsigned char> recursive_difference_mask(const BaseData&d,int maxD){auto st=base_stats(d.A);vector<unsigned char>diff((size_t)maxD+1);auto mark=[&](long long x){if(x>0&&x<=maxD)diff[x]=1;};mark(R8);mark(2LL*R8);for(int x=1;x<(int)st.cnt.size();x++)if(st.cnt[x]){mark(x);for(int k=1;k<=2;k++){mark(1LL*k*R8+x);mark(llabs(1LL*k*R8-x));}}for(int x:d.s9)mark(x);return diff;}
void mode_domains(const string&support,const string&out4){auto [low,D]=load_bits(support);if(low!=0)throw runtime_error("support low");auto d=data();auto diff=recursive_difference_mask(d,2*MAX_R4);for(int factor:{2,4}){int mr=factor==2?MAX_R2:MAX_R4;long long sponsor=0,dis=0,cov=0;vector<int>rem;for(int R=1;R<=mr;R++)if(v2(R)%2==0){sponsor++;if(!diff[R]&&!diff[2LL*R]){dis++;if(bit(D,R)||bit(D,2LL*R)||bit(D,3LL*R))cov++;else rem.push_back(R);}}if(factor==2){if(sponsor!=6316608||dis!=2967413||cov!=2967413||!rem.empty())throw runtime_error("factor2 domain mismatch");}else{if(sponsor!=51055851||dis!=39459384||cov!=30221222||rem.size()!=9238162)throw runtime_error("factor4 domain mismatch");write_list(out4,rem);}cout<<"factor="<<factor<<" sponsor="<<sponsor<<" disjoint="<<dis<<" completion="<<cov<<" remaining="<<rem.size()<<"\n";}}
void mode_delta0(const string&in,const string&out){auto targets=read_list(in);auto d=data();auto diff=recursive_difference_mask(d,MAX_R4);vector<int>rem;for(int r:targets){if((r&1)||!diff[r/2])rem.push_back(r);}write_list(out,rem);cout<<"delta0_covered="<<targets.size()-rem.size()<<" remaining="<<rem.size()<<"\n";}
vector<int> group_starts(const BaseData&d,int delta){int M=d.A.back();vector<unsigned char>present(M+1);for(int a:d.A)present[a]=1;vector<int>X;X.reserve(100000);auto add=[&](long long z,int copies){long long ad=llabs(z);if(ad>M)return;if(ad==0){for(int i=0;i<copies;i++)for(int a:d.A)X.push_back(L9+a+i*R8);return;}for(int u:d.A){if((long long)u+ad>M||!present[u+ad])continue;int a=z>0?u:u+ad;for(int i=0;i<copies;i++)X.push_back(L9+a+i*R8);}};add(delta,3);add(1LL*delta-R8,2);add(1LL*delta-2LL*R8,1);if(delta<=S9_MAX&&binary_search(d.s9.begin(),d.s9.end(),delta))X.push_back(0);sort(X.begin(),X.end());X.erase(unique(X.begin(),X.end()),X.end());return X;}
void mode_transpose(const string&in,const string&deltas,const string&out){auto d=data();auto targets=read_list(in),wanted=read_list(deltas);sort(wanted.begin(),wanted.end());wanted.erase(unique(wanted.begin(),wanted.end()),wanted.end());int hi=targets.back();vector<unsigned char>target(hi+1),covered(hi+1);for(int r:targets)target[r]=1;long long ops=0;for(int delta:wanted){if(delta<=0)continue;auto X=group_starts(d,delta);for(int i=0;i<(int)X.size();i++)for(int j=0;j<=i;j++){long long D=1LL*X[i]-X[j],p=2*D+delta,m=2*D-delta;if(p<=hi&&target[p])covered[p]=1;if(m>0&&m<=hi&&target[m])covered[m]=1;ops++;}}vector<int>rem;for(int r:targets)if(!covered[r])rem.push_back(r);write_list(out,rem);cout<<"transpose_deltas="<<wanted.size()<<" covered="<<targets.size()-rem.size()<<" remaining="<<rem.size()<<" ops="<<ops<<"\n";}
void build_group_catalog(const BaseData&d,const Stats&st,int lo,int hi,int lower_count,int upper_count,vector<int>&ds,vector<int>&cs){int M=d.A.back(),n=d.A.size(),MAX=S9_MAX;vector<unsigned char>inS(MAX+1);for(int x:d.s9)inS[x]=1;for(int delta=1;delta<=MAX;delta++){long long c=0;int a0=INT_MAX,a1=INT_MIN;auto add=[&](long long cc,long long x,long long y){if(!cc)return;c+=cc;a0=min(a0,(int)x);a1=max(a1,(int)y);};if(delta<=M&&st.cnt[delta])add(3LL*st.cnt[delta],L9+st.mn[delta],L9+st.mx[delta]+2LL*R8);long long z=1LL*delta-R8,ad=llabs(z);if(ad<=M){long long oc=ad==0?n:st.cnt[ad];if(oc){int u=ad==0?0:(z>0?st.mn[ad]:st.mn[ad]+ad),v=ad==0?M:(z>0?st.mx[ad]:st.mx[ad]+ad);add(2*oc,L9+u,L9+v+R8);}}z=1LL*delta-2LL*R8;ad=llabs(z);if(ad<=M){long long oc=ad==0?n:st.cnt[ad];if(oc){int u=ad==0?0:(z>0?st.mn[ad]:st.mn[ad]+ad),v=ad==0?M:(z>0?st.mx[ad]:st.mx[ad]+ad);add(oc,L9+u,L9+v);}}if(inS[delta])add(1,0,0);if(c<=lower_count||c>upper_count)continue;long long span=1LL*a1-a0;bool relevant=(delta<=hi&&2*span+delta>=lo)||(2*span-delta>=lo);if(relevant){ds.push_back(delta);cs.push_back((int)c);}}}
vector<int> materialize_starts(const BaseData&d,const Stats&st,const vector<int>&ds,const vector<int>&cs,vector<uint64_t>&off){vector<int>id(S9_MAX+1,-1);for(int i=0;i<(int)ds.size();i++)id[ds[i]]=i;off.assign(ds.size()+1,0);for(size_t i=0;i<ds.size();i++)off[i+1]=off[i]+cs[i];vector<uint64_t>cur=off;vector<int>starts(off.back());auto put=[&](int delta,int x){if(delta>=0&&delta<=S9_MAX){int k=id[delta];if(k>=0)starts[cur[k]++]=x;}};int n=d.A.size();for(int i=0;i<n;i++)for(int j=i+1;j<n;j++){int q=d.A[j]-d.A[i];if(id[q]>=0){put(q,L9+d.A[i]);put(q,L9+d.A[i]+R8);put(q,L9+d.A[i]+2*R8);}}for(int a:d.A)for(int b:d.A){int q=R8+b-a;if(q>0&&q<=S9_MAX&&id[q]>=0){put(q,L9+a);put(q,L9+a+R8);}q=2*R8+b-a;if(q>0&&q<=S9_MAX&&id[q]>=0)put(q,L9+a);}for(int g:d.g9)put(L9+g,0);for(size_t i=0;i<ds.size();i++)if(cur[i]!=off[i+1])throw runtime_error("start fill mismatch");return starts;}
void mode_band(const string&in,int lower_count,int upper_count,const string&out,bool target_mode){auto targets=read_list(in);if(targets.empty())throw runtime_error("empty targets");auto d=data();auto st=base_stats(d.A);int lo=targets.front(),hi=targets.back();vector<int>ds,cs;build_group_catalog(d,st,lo,hi,lower_count,upper_count,ds,cs);vector<uint64_t>off;auto starts=materialize_starts(d,st,ds,cs,off);vector<unsigned char>target(hi+1),covered(hi+1);for(int r:targets)target[r]=1;long long ops=0;auto hasdiff=[&](int*x,int c,long long D){if(D<0)return false;if(D==0)return c>0;int i=0,j=1;while(j<c){long long q=1LL*x[j]-x[i];if(q==D)return true;if(q<D)j++;else{i++;if(i==j)j++;}}return false;};for(size_t k=0;k<ds.size();k++){int delta=ds[k],c=cs[k];int*x=starts.data()+off[k];sort(x,x+c);if(!target_mode){for(int i=0;i<c;i++)for(int j=0;j<=i;j++){long long D=1LL*x[i]-x[j],p=2*D+delta,m=2*D-delta;if(p<=hi&&target[p])covered[p]=1;if(m>0&&m<=hi&&target[m])covered[m]=1;ops++;}}else{for(int r:targets){if(covered[r])continue;bool ok=false;if(((r-delta)&1)==0){long long D=(1LL*r-delta)/2;if(D>=0){ops+=c;ok=hasdiff(x,c,D);}}if(!ok&&((r+delta)&1)==0){long long D=(1LL*r+delta)/2;ops+=c;ok=hasdiff(x,c,D);}if(ok)covered[r]=1;}}}vector<int>rem;for(int r:targets)if(!covered[r])rem.push_back(r);write_list(out,rem);cout<<(target_mode?"target_band":"band")<<" lower="<<lower_count<<" upper="<<upper_count<<" groups="<<ds.size()<<" starts="<<starts.size()<<" covered="<<targets.size()-rem.size()<<" remaining="<<rem.size()<<" ops="<<ops<<"\n";}
void mode_final(const string&in){auto rs=read_list(in);const vector<int>expected={74090852,76281492,76460249,76468444,76468753,76519853,76561979};const vector<array<int,4>>w={{78873376,114755138,150636900,186518662},{77131832,115110758,153089684,191068610},{76861739,114934018,153006297,191078576},{76869934,114942213,153014492,191086771},{76869589,114942195,153014801,191087407},{76776212,115078719,153381226,191683733},{77081746,115247623,153413500,191579377}};if(rs!=expected)throw runtime_error("terminal list mismatch");auto d=data();for(size_t i=0;i<rs.size();i++){auto g=raw(d.s9,rs[i]);unordered_set<int>s(g.begin(),g.end());int q=w[i][1]-w[i][0];if(q<=0||w[i][2]-w[i][1]!=q||w[i][3]-w[i][2]!=q)throw runtime_error("bad explicit AP");for(int x:w[i])if(!s.count(x))throw runtime_error("explicit AP absent");}cout<<"verified_terminal_candidates=7\nN_9_2=0\nN_9_4=0\n";}
void mode_check(const string&p,long long count,uint64_t hash){auto v=read_list(p);if((long long)v.size()!=count||fnv(v)!=hash)throw runtime_error("list check mismatch");cout<<"checked="<<p<<" count="<<v.size()<<" fnv64="<<hex<<fnv(v)<<dec<<"\n";}
}
int main(int argc,char**argv){try{if(argc<2)throw runtime_error("mode required");string m=argv[1];if(m=="state"){auto d=data();cout<<"S9_size="<<d.s9.size()<<" S9_fnv64="<<hex<<fnv(d.s9)<<dec<<"\n";}else if(m=="completions"&&argc==3)mode_completions(argv[2]);else if(m=="correlate"&&argc==6)mode_correlate(argv[2],stoi(argv[3]),stoi(argv[4]),argv[5]);else if(m=="reduce"&&argc>=4)mode_reduce(argv[2],argc,argv,3);else if(m=="domains"&&argc==4)mode_domains(argv[2],argv[3]);else if(m=="transpose"&&argc==5)mode_transpose(argv[2],argv[3],argv[4]);else if(m=="delta0"&&argc==4)mode_delta0(argv[2],argv[3]);else if((m=="band"||m=="target-band")&&argc==6)mode_band(argv[2],stoi(argv[3]),stoi(argv[4]),argv[5],m=="target-band");else if(m=="final"&&argc==3)mode_final(argv[2]);else if(m=="check"&&argc==5)mode_check(argv[2],stoll(argv[3]),stoull(argv[4],nullptr,16));else throw runtime_error("bad arguments");return 0;}catch(const exception&e){cerr<<"error: "<<e.what()<<"\n";return 1;}}
